In [5]:
#pip install pandas
import pandas as pd

In [13]:
df = pd.read_csv('DimCustomer.csv')

In [14]:
# 1. carregue um csv em formato dataframe 
df = pd.read_csv("DimCustomer.csv")

In [15]:
# 2. veja as cinco primeiras e cinco ultimas linhas 
df.head()

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
0,0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0
2,2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0
3,3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0

In [16]:
df.tail()

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
18864,18864,19141,731,Not Provided,Not Provided,1970-02-01,M,F,10000000.0,2.0,1.0,Bachelors,Management,1.0,0.0
18865,18865,19142,732,Not Provided,Not Provided,1989-02-16,S,F,10000000.0,1.0,1.0,Bachelors,Manual,1.0,0.0
18866,18866,19143,733,Not Provided,Not Provided,1980-07-23,M,M,10000000.0,3.0,1.0,Graduate Degree,Management,1.0,2.0
18867,18867,19144,734,Not Provided,Not Provided,1982-08-28,M,M,10000000.0,1.0,0.0,Partial College,Management,0.0,1.0
18868,18868,19145,735,Not Provided,Not Provided,1967-06-19,S,M,10000000.0,5.0,5.0,Partial High School,Clerical,1.0,2.0

In [17]:
# 3. verifique o nome das colunas, quantidade de linhas e colunas 
print("colunas:", df.columns)

colunas: Index(['Unnamed: 0', 'CustomerKey', 'GeographyKey', 'FirstName', 'LastName',
       'BirthDate', 'MaritalStatus', 'Gender', 'YearlyIncome', 'TotalChildren',
       'NumberChildrenAtHome', 'Education', 'Occupation', 'HouseOwnerFlag',
       'NumberCarsOwned'],
      dtype='str')

In [18]:
print("quantidade de linhas e colunas:", df.shape)

quantidade de linhas e colunas: (18869, 15)

In [22]:
# 4. filtre por salario anual maior que 150000
df_maior_150000 = df[df["YearlyIncome"]>150000]

In [30]:
# 5. calcule a media da coluna YearlyIncome
media_salario = df["YearlyIncome"].mean()
print(f"A media do salario anual é: {media_salario}")

A media do salario anual é: 260174.8900312682