In [1]:
import pandas as pd

In [5]:
csv_file_path = '/content/sample_data/california_housing_train.csv'
df = pd.read_csv(csv_file_path)

In [6]:
display(df.head())

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [7]:
display(df.tail())

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [8]:
filtered_df = df[df['median_house_value'] > 150000]
print("DataFrame filtrado (median_house_value > 150000):")
display(filtered_df.head())

DataFrame filtrado (median_house_value > 150000):

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
100,-115.59,32.79,8.0,2183.0,307.0,1000.0,287.0,6.3814,159900.0
146,-116.18,33.69,17.0,89.0,19.0,79.0,21.0,2.3750,155000.0
172,-116.26,33.65,3.0,7437.0,1222.0,574.0,302.0,10.2948,382400.0
175,-116.29,33.74,6.0,12991.0,2555.0,4571.0,1926.0,4.7195,199300.0
176,-116.29,33.72,5.0,3584.0,760.0,1097.0,470.0,3.1771,167400.0

In [10]:
mean_population = df['population'].mean()
print(f"A média da população em toda a tabela é: {mean_population:.2f}")

A média da população em toda a tabela é: 1429.57