In [ ]:
%pip install pandas
import pandas as pd
from pathlib import Path

arquivo = Path("DimCustomer.csv")
dados = pd.read_csv(arquivo)

print(f"Arquivo aberto: {arquivo}")
print(f"Linhas e colunas: {dados.shape}")
display(dados.head())

df = pd.read_csv('DimCustomer.csv')

df["MaritalStatus"].value_counts()

df.describe()

#1. carregue um csv em formato dataframe
#2. veja as cinco primeiras e cinco ultimas linhas
#3. verifique o nome das colunas, quantidade de linhas e colunas
#4. filtre por salario anual maior que 150000 
#5. calcule a media da coluna YearlyIncome

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\silme\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\silme\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\silme\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\silme\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\silme\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Arquivo aberto: DimCustomer.csv
Linhas e colunas: (18869, 15)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: C:\Users\silme\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
0,0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0
2,2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0
3,3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0

,Unnamed: 0,CustomerKey,GeographyKey,YearlyIncome,TotalChildren,NumberChildrenAtHome,HouseOwnerFlag,NumberCarsOwned
count,18869.00000,18869.000000,18869.000000,1.886900e+04,18869.000000,18869.000000,18869.000000,18869.000000
mean,9434.00000,9440.631459,574.910435,2.601749e+05,1.856219,1.034077,0.673274,1.513753
std,5447.15545,5456.841811,84.163867,1.406071e+06,1.615868,1.541922,0.469029,1.146417
min,0.00000,1.000000,423.000000,1.000000e+04,0.000000,0.000000,0.000000,0.000000
25%,4717.00000,4718.000000,506.000000,3.000000e+04,0.000000,0.000000,0.000000,1.000000
50%,9434.00000,9435.000000,568.000000,6.000000e+04,2.000000,0.000000,1.000000,2.000000
75%,14151.00000,14152.000000,645.000000,8.000000e+04,3.000000,2.000000,1.000000,2.000000
max,18868.00000,19145.000000,952.000000,1.000000e+07,5.000000,5.000000,1.000000,4.000000