In [2]:
import pandas as pd

In [ ]:
#Carregando o arquivo CSV para um DataFrame
df = pd.read_csv('DimCustomer.csv')

In [ ]:
#Consultar as 5 primeiras e as 5 últimas linhas do DataFrame
df

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
0,0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0
2,2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0
3,3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18864,18864,19141,731,Not Provided,Not Provided,1970-02-01,M,F,10000000.0,2.0,1.0,Bachelors,Management,1.0,0.0
18865,18865,19142,732,Not Provided,Not Provided,1989-02-16,S,F,10000000.0,1.0,1.0,Bachelors,Manual,1.0,0.0
18866,18866,19143,733,Not Provided,Not Provided,1980-07-23,M,M,10000000.0,3.0,1.0,Graduate Degree,Management,1.0,2.0
18867,18867,19144,734,Not Provided,Not Provided,1982-08-28,M,M,10000000.0,1.0,0.0,Partial College,Management,0.0,1.0
18868,18868,19145,735,Not Provided,Not Provided,1967-06-19,S,M,10000000.0,5.0,5.0,Partial High School,Clerical,1.0,2.0

In [ ]:
#Verificar o nome das colunas e quantidade de linhas e colunas do DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18869 entries, 0 to 18868
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            18869 non-null  int64
 1   CustomerKey           18869 non-null  int64
 2   GeographyKey          18869 non-null  int64
 3   FirstName             18869 non-null  str
 4   LastName              18869 non-null  str
 5   BirthDate             18869 non-null  str
 6   MaritalStatus         18869 non-null  str
 7   Gender                18869 non-null  str
 8   YearlyIncome          18869 non-null  float64
 9   TotalChildren         18869 non-null  float64
 10  NumberChildrenAtHome  18869 non-null  float64
 11  Education             18869 non-null  str
 12  Occupation            18869 non-null  str
 13  HouseOwnerFlag        18869 non-null  float64
 14  NumberCarsOwned       18869 non-null  float64
dtypes: float64(5), int64(3), str(7)
memory usage: 2.2 MB

In [ ]:
#Filtrar por salario anual maior que 150.000
df[df['YearlyIncome'] > 150000]

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
79,79,80,632,Donald,Gonzalez,1959-03-11,S,M,160000.0,0.0,0.0,Graduate Degree,Management,1.0,2.0
80,80,81,531,Damien,Chander,1959-07-17,M,M,170000.0,0.0,0.0,Graduate Degree,Management,1.0,2.0
180,180,181,610,April,Anand,1943-01-02,M,F,160000.0,1.0,3.0,Bachelors,Management,1.0,4.0
181,181,182,653,Devin,Martin,1943-08-08,M,M,170000.0,2.0,3.0,Graduate Degree,Management,1.0,2.0
240,240,241,704,Anne,Hernandez,1958-12-11,M,F,160000.0,2.0,3.0,Partial College,Professional,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18864,18864,19141,731,Not Provided,Not Provided,1970-02-01,M,F,10000000.0,2.0,1.0,Bachelors,Management,1.0,0.0
18865,18865,19142,732,Not Provided,Not Provided,1989-02-16,S,F,10000000.0,1.0,1.0,Bachelors,Manual,1.0,0.0
18866,18866,19143,733,Not Provided,Not Provided,1980-07-23,M,M,10000000.0,3.0,1.0,Graduate Degree,Management,1.0,2.0
18867,18867,19144,734,Not Provided,Not Provided,1982-08-28,M,M,10000000.0,1.0,0.0,Partial College,Management,0.0,1.0
18868,18868,19145,735,Not Provided,Not Provided,1967-06-19,S,M,10000000.0,5.0,5.0,Partial High School,Clerical,1.0,2.0

In [ ]:
#Calcular a média da coluna 'YearlyIncome'
media_salaria = df['YearlyIncome'].mean()

print(f'A média anual salarial é: R${round (media_salaria, 2)}')

A média anual salarial é: R$260174.89

In [25]:
media_salaria

np.float64(260174.8900312682)